#pragma once

#define ACTOR_CHANNEL_CLASS "Class Engine.ActorChannel"
#define TO_STRING(val) std::to_string(val)

#define PLAYER_CLASS APlayerPawn_Generic_C
#define PLAYER_CONTROLLER_CLASS AFortPlayerController
#define PLAYER_STATE_CLASS AFortPlayerState

#define GOBJECTS_OFFSET 0x44E5CE0
#define FNAMETOSTRING_OFFSET 0xC79B10
#define FREEMEMORY_OFFSET 0xBBCEB0

#define INITHOST_OFFSET 0x27B4820
#define UWORLD_NCM_OFFSET 0x1DA15C0
#define AONLINEBEACONHOST_NCM_OFFSET 0x27B7620
#define WELCOME_PLAYER_OFFSET 0x1DACC50
#define SPAWN_PLAY_ACTOR_OFFSET 0x1A9E7B0
#define SET_CHANNEL_ACTOR_OFFSET 0x19AA960
#define CREATE_CHANNEL_OFFSET 0x1B0C510
#define REPLICATE_ACTOR_OFFSET 0x19A60D0
#define CLIENT_SEND_AUDJUSTMENTS_OFFSET 0x1C1D490